repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.97.3 # https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt
        files: \.tf$
      - id: terraform_validate
        files: \.tf$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0 # https://github.com/pre-commit/pre-commit-hooks/releases
    hooks:
      - id: trailing-whitespace # 行末空白を削除
      - id: end-of-file-fixer   # EOFの空行を調整
        exclude: 'credentials\.yml\.enc'
      - id: detect-private-key  # 秘密鍵の漏洩防止
