services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./db/docker/db.env

  api:
    build:
      target: development
      args:
        DEV_API_PORT: $DEV_API_PORT
    env_file:
      - ./api/docker/api.env
    ports:
      - "$DEV_API_PORT:$DEV_API_PORT"
    volumes:
      - ./api:/home/$API_USER_NAME/api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s --port $DEV_API_PORT --binding '0.0.0.0'"
    tty: true
    stdin_open: true
    depends_on:
      - db

  web:
    container_name: web-container
    build:
      target: development
    ports:
      - "$DEV_WEB_PORT:$DEV_WEB_PORT"
    env_file:
      - ./web/docker/web.env
    volumes:
      - ./web:/home/node/web
    tty: true
    stdin_open: true

volumes:
  db-data:
    name: ${PROJECT_NAME}_db-data
