services:
  api:
    container_name: api-container
    build:
      context: ./api
      dockerfile: docker/Dockerfile
      args:
        RUBY_VER: $RUBY_VER
        USER_ID: $USER_ID
        GROUP_ID: $GROUP_ID
        USER_NAME: $API_USER_NAME
        GROUP_NAME: $API_GROUP_NAME
        BUNDLE_PATH: $BUNDLE_PATH
        BUNDLE_BIN: $BUNDLE_BIN
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s --port $DEV_API_PORT --binding '0.0.0.0'"
    tty: true
    stdin_open: true

  web:
    container_name: web-container
    build:
      context: ./web
      dockerfile: docker/Dockerfile
      args:
        NODE_VER_ARG: $NODE_VER
        USER_ID: $USER_ID
        GROUP_ID: $GROUP_ID
        USER_NAME: $WEB_USER_NAME
        GROUP_NAME: $WEB_GROUP_NAME
    tty: true
    stdin_open: true
    depends_on:
      - api
